config/routes.rb
Rails.application.routes.draw do
  get 'admin/competences'

  get "site/index"

  get "/login", to: "site#login", as: "login"

  get "/logout", to: "site#logout", as: "logout"

  get "/competences", to: "competences#index", as: "competences"

  get "/employees", to: "employees#index", as: "employees"

  get ':controller(/:action(/:id))'

  post ':controller(/:action(/:id))'

  root "site#index"

end

app/models/color.rb
class Color < ActiveRecord::Base
  has_many :competence_groups

  def self.option_for_select
    all = Color.all
    r_ary = []
    all.each do |color|
      r_ary << [color.name, color.id, data: {color: "#{color.first}"}]
    end
    r_ary
  end
end

app/models/competence.rb
class Competence < ActiveRecord::Base
  belongs_to :competence_group
  has_many :competence_levels
  has_many :competence_knowskills
end

app/models/competence_group.rb
class CompetenceGroup < ActiveRecord::Base
  belongs_to :color
  has_many :competences
end

app/models/competence_knowskill.rb
class CompetenceKnowskill < ActiveRecord::Base
  belongs_to :competence
end

app/models/competence_level.rb
class CompetenceLevel < ActiveRecord::Base
  belongs_to :competence
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :subordinates, class_name: "Employee", foreign_key: :director_id
  belongs_to :director, class_name: "Employee"

  def self.tree(user_id = nil, with_colleagues = true)
    @all ||= self.all.order(:fired, :fio)
    tree = {}
    if user_id
      tree[:user] = @all.select {|e| e.id == user_id}[0]
    else
      tree[:user] = @all.select {|e| e.director_id.nil?}[0]
    end
    tree[:colleagues] = get_colleagues(tree[:user]) if with_colleagues
    tree[:subordinates] = get_subordinates(tree[:user])
    tree
  end

  private

  def self.get_subordinates(user)
    return_ary = []
    @all.select {|e| e.director_id == user.id && e.id != user.id}.each do |subordinate|
      return_ary << tree(subordinate.id, false)
    end
    return_ary
  end

  def self.get_colleagues(user)
    return_ary = []
    @all.select { |employee| employee.director_id == user.director_id && employee.id != user.id }.each do |colleague|
      if @all.select {|e| e.director_id == user.id}.count > 0
        # если я директор, то могу видеть коллег (сотрудников, у которых со мной один директор), которые являются как руководителями, так и нет
        return_ary << tree(colleague.id, false)
      else
        # если я не директор, то могу видеть коллег (сотрудников, у которых со мной один директор), которые не являются руководителями
        return_ary << tree(colleague.id, false) if @all.select {|e| e.director_id == colleague.id}.count == 0
      end
    end
    return_ary
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def competences
    @groups = CompetenceGroup.all.order(:position).where(deleted: false)
  end

  def new_competence_group
    @group = CompetenceGroup.new
    @group.color = Color.find_by_name("Asbestos")

    @group.position = params[:position].to_i + 1

    respond_to do |format|
      format.html { render partial: "admin/competence_group", locals: {group: @group } }
      format.js { render partial: "admin/competence_group", locals: {group: @group } }
    end
  end

  def update_competence_groups
    groups = competence_groups_params[:groups]

    groups.each do |key, group|
      if group["id"]
        CompetenceGroup.update(group["id"].to_i, color_id: group["color"].to_i, position: group["position"].to_i, name: group["name"].capitalize, visible: group["visible"].to_b, deleted: group["deleted"].to_b)
      else
        CompetenceGroup.create(color_id: group["color"].to_i, position: group["position"].to_i, name: group["name"].capitalize, visible: group["visible"].to_b, deleted: group["deleted"].to_b)
      end
    end

    render text: "success"
  end

  private

  def competence_groups_params
    params.permit(groups: [:id, :color, :position, :visible, :deleted, :name])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/competences_controller.rb
class CompetencesController < ApplicationController
  def index
    @competence_groups = CompetenceGroup.all.where(visible: true, deleted: false).order(:position)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.tree
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end

  def login
    session[:user_id] = 1
    session[:user_role] = "User"
    redirect_to root_path
  end

  def logout
    session[:user_id] = nil
    session[:user_role] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/admin/_competence.html.haml
.panel.panel-default{style: "background-color: #{group.color.second}"}
  .panel-body
    = content_tag(:strong, [group.position].pack("U") + "." + competence.position.to_s + ". ")
    = text_field_tag "competence_name", competence.name, class: "form-control competence_input", disabled: !competence.visible

app/views/admin/_competence_group.html.haml
.panel.panel-default.admin_competence_group{class: !group.visible && "competence_invisible", data: {group: {id: group.id, position: group.position, visible: group.visible.to_s, deleted: group.deleted.to_s}}, style: "background-color: #{group.color.first}"}
  .panel-body
    = content_tag(:strong, [group.position].pack("U") + ". ")
    = text_field_tag "group_name", group.name, class: "form-control competence_input", disabled: !group.visible
    = select_tag "group_color", options_for_select(Color.option_for_select, group.color_id), class: "form-control competence_input", disabled: !group.visible
    %button.btn.btn-default.pull-right.group_competence_delete{disabled: !group.visible} Удалить
    %button.btn.btn-default.pull-right.group_competence_hide{style: "margin-right: 10px#{group.visible ? "" : "; display: none"}"} Скрыть
    %button.btn.btn-default.pull-right.group_competence_show{style: "margin-right: 10px#{group.visible ? "; display: none" : ""}"} Показать

app/views/admin/competences.html.haml
%h2 Администрирование групп компетенций
.panel.panel-default
  .panel-heading
    %h3.panel-title Группы компетенций
  .panel-body#admin_competence_groups
    - @groups.each do |group|
      = render "competence_group", group: group
  .panel-footer
    %button.btn.btn-primary#add_competence_group{data: {remote: true}} Добавить группу компетенций
    %button.btn.btn-danger.pull-right#competence_group_cancel Отменить
    %button.btn.btn-success.pull-right#competence_group_apply{style: "margin-right: 10px"} Применить
    .clearfix

%h2 Администрирование компетенций
- @groups.each do |group|
  .panel.panel-default
    .panel-heading{style: "background-color: #{group.color.first}"}
      %h3.panel-title= [group.position].pack("U") + ". " + group.name
    .panel-body
      - group.competences.each do |competence|
        = render "competence", group: group, competence: competence
    .panel-footer
      %button.btn.btn-primary.add_competence{data: {remote: true}} Добавить компетенцию
      %button.btn.btn-danger.pull-right.competence_cancel Отменить
      %button.btn.btn-success.pull-right.competence_apply{style: "margin-right: 10px"} Применить
      .clearfix

app/views/competences/index.html.haml
#competence_groups
  - @competence_groups.each do |cg|
    .competence_group
      .competence_group_header{style: "background-color: #{cg.color.first}"}
        = [cg.position].pack("U") + ". " + cg.name
        .competence_level_title.pull-right Уровни
      .competences{style: "background-color: #{cg.color.second}"}
        - cg.competences.each do |c|
          .competence
            .competence_header.finger
              .competence_hover.plus
              = [cg.position].pack("U") + "." + c.position.to_s + ". " + c.name
              .competence_levels.pull-right
                - c.competence_levels.order("level DESC").each do |level|
                  - if level.visible
                    .competence_level.pull-right{style: "background-color: #{cg.color.first}"}
                      = level.level
                  - else
                    .competence_level.pull-right{style: "background-color: white"}
            .competence_description{style: "background-color: #{cg.color.third}"}
              %i
                %uОписание компетенции:
              %p{style: "margin: 0px"}
                = c.description
              %i
                %uОписание уровней компетенции:
              - c.competence_levels.order(:level).each do |level|
                - if level.visible
                  %dl{style: "margin: 0px"}
                    %dt Уровень #{level.level} (#{level.points} баллов)
                    %dd #{level.description}

app/views/employees/_user.haml
.panel.panel-default{class: show_body.eql?(false) && "panel-collapse",  data: {user_id: "#{employee[:user].id}"}}
  .panel-heading.finger
    %h3.panel-title
      - if employee[:user].fired
        = content_tag(:s, employee[:user].fio)
      - else
        = employee[:user].fio
  .panel-body
    %ul.nav.nav-tabs{role: "tablist"}
      %li.active= link_to 'Компетенции', "#user_competences_tab", role: "tab", data: {toggle: "tab"}
      %li= link_to 'Знания, умения, навыки', "#user_knowskills_tab", role: "tab", data: {toggle: "tab"}
      %li= link_to 'Обучение', "#user_educations_tab", role: "tab", data: {toggle: "tab"}
    .tab-content
      .tab-pane.active#user_competences_tab Содержание таба "Компетенции"
      .tab-pane#user_knowskills_tab Содержание таба "Знания, умения, навыки"
      .tab-pane#user_educations_tab Содержание таба "Обучение"
      %hr
    - employee[:subordinates].each do |subordinate|
      = render "employees/user", employee: subordinate, show_body: false

app/views/employees/index.haml
= render "employees/user", employee: @employees, show_body: true
- @employees[:colleagues].each do |colleague|
  = render "employees/user", employee: colleague, show_body: false

app/views/layouts/_user.html.haml
%ul.nav.navbar-nav
  %li{class: controller_name.eql?("employees") && "active"}
    = link_to "Сотрудники", "http://127.0.0.1:3000/employees"
  -#%li{class: controller_name.eql?("projects") && "active"}
  -#  = link_to "Проекты", "http://127.0.0.1:3000/projects"
  -#%li{class: controller_name.eql?("educations") && "active"}
  -#  = link_to "Обучение", "http://127.0.0.1:3000/educations"
  %li{class: controller_name.eql?("competences") && "active"}
    = link_to "Компетенции", competences_path
  %li.dropdown{class: controller_name.eql?("admin") && "active"}
    = link_to "Администрирование", competences_path, class: "dropdown-toggle", data: {toggle: "dropdown"}
    %ul.dropdown-menu{role: "menu"}
      %li= link_to "Компетенции", admin_competences_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EcompRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title e-Competences
    <link href='http://fonts.googleapis.com/css?family=Ubuntu&subset=cyrillic,latin' rel='stylesheet' type='text/css'>
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default{role: "navigation"}
      .container-fluid
        .navbar-header
          %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: "#bs-example-navbar-collapse-1"}}
            %span.sr-only Toggle navigation
            - 3.times do
              %span.icon-bar
          = link_to "e-Competences", root_url, class: "navbar-brand"
        .collapse.navbar-collapse#bs-example-navbar-collapse-1
          = render "layouts/user" unless session[:user_id].nil?
          = link_to "Войти", login_path, class: "btn btn-default navbar-btn pull-right", type: "button" if session[:user_id].nil?
          = link_to "Выйти", logout_path, class: "btn btn-danger navbar-btn pull-right", type: "button" unless session[:user_id].nil?
    .col-lg-10.col-lg-offset-1
      #content
        = yield
    #toTop.finger
      %i.glyphicon.glyphicon-circle-arrow-up